/// One subtitle track for a YouTube video.
class YoutubeCaption {
  /// BCP-47-ish code from YouTube, e.g. "en", "es", "pt-BR".
  final String code;

  /// YouTube's own name for the language, e.g. "English".
  final String label;

  /// WebVTT URL. Not YouTube's default format: its timedtext endpoint serves
  /// XML unless asked otherwise, and mpv can't read that.
  final String vttUrl;

  /// Speech-recognition captions rather than authored ones. Worth marking:
  /// they're noticeably worse, and YouTube lists them alongside real ones.
  final bool isAutoGenerated;

  const YoutubeCaption({
    required this.code,
    required this.label,
    required this.vttUrl,
    this.isAutoGenerated = false,
  });

  String get displayLabel => isAutoGenerated ? '$label (auto-generated)' : label;
}
